import os
import datetime
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from typing import Dict, Any, Optional

app = FastAPI(title="KrokBot Web Dashboard", version="1.0.0")

scheduler_manager_ref: Optional[Any] = None
agent_instance_ref: Optional[Any] = None

def set_scheduler_manager(manager):
    global scheduler_manager_ref
    scheduler_manager_ref = manager

def set_agent_instance(agent):
    global agent_instance_ref
    agent_instance_ref = agent

static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.exists(static_dir):
    app.mount("/static", StaticFiles(directory=static_dir), name="static")

@app.get("/", response_class=HTMLResponse)
def get_dashboard():
    index_file = os.path.join(static_dir, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return "<h1>KrokBot Workstation Dashboard</h1>"

@app.get("/api/metrics")
def get_metrics():
    import psutil
    return {
        "cpu_percent": psutil.cpu_percent(interval=0.1),
        "memory_percent": psutil.virtual_memory().percent
    }

@app.get("/api/schedules")
def get_schedules():
    if scheduler_manager_ref:
        return scheduler_manager_ref.get_all_schedules()
    return []

@app.post("/api/schedules")
def create_schedule(payload: Dict[str, Any]):
    if not scheduler_manager_ref:
        raise HTTPException(status_code=500, detail="Scheduler manager not initialized")
    name = payload.get("name", "Scheduled Health Task")
    cron_expr = payload.get("cron_expression", "0 * * * *")
    prompt = payload.get("prompt", "Check system health")
    item = scheduler_manager_ref.add_schedule(name, cron_expr, prompt)
    return item

@app.delete("/api/schedules/{schedule_id}")
def delete_schedule(schedule_id: str):
    if not scheduler_manager_ref:
        raise HTTPException(status_code=500, detail="Scheduler manager not initialized")
    success = scheduler_manager_ref.remove_schedule(schedule_id)
    return {"status": "success" if success else "error"}

@app.post("/api/chat")
def chat_endpoint(payload: Dict[str, Any]):
    prompt = payload.get("prompt", "")
    if not prompt:
        raise HTTPException(status_code=400, detail="Prompt is required")
    
    if agent_instance_ref:
        result = agent_instance_ref.run_task(prompt)
        return {
            "status": "success",
            "prompt": prompt,
            "reply": result.get("report", ""),
            "metrics": result.get("metrics", {}),
            "sandbox_output": result.get("sandbox_output", {})
        }
    else:
        # Fallback response for standalone testing
        return {
            "status": "success",
            "prompt": prompt,
            "reply": f"KrokBot executed task: '{prompt}'. Workstation health check completed successfully.",
            "metrics": {"cpu_percent": 15.0, "memory_percent": 45.0},
            "sandbox_output": {"exit_code": 0, "stdout": "[SANDBOX DIAGNOSTIC] Complete."}
        }

def export_health_report(filepath: str, report_content: str, metrics: Dict[str, Any]) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md_text = f"""# KrokBot Workstation Health Report

**Generated**: {now}  
**OS Info**: {metrics.get('os_info', 'Unknown OS')}  

---

## System Metrics Baseline
* **CPU Usage**: {metrics.get('cpu_percent', 'N/A')}%
* **Memory Usage**: {metrics.get('memory_percent', 'N/A')}%

---

## Agent Diagnostic Summary

{report_content}

---
*Report generated by KrokBot Autonomous Diagnostic Agent.*
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_text)
