import os
import datetime
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from typing import Dict, Any

app = FastAPI(title="KrokBot Web Dashboard", version="1.0.0")

static_dir = os.path.join(os.path.dirname(__file__), "static")
if os.path.exists(static_dir):
    app.mount("/static", StaticFiles(directory=static_dir), name="static")

@app.get("/", response_class=HTMLResponse)
def get_dashboard():
    index_file = os.path.join(static_dir, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return "<h1>KrokBot Workstation Dashboard</h1>"

@app.get("/api/metrics")
def get_metrics():
    import psutil
    return {
        "cpu_percent": psutil.cpu_percent(interval=0.1),
        "memory_percent": psutil.virtual_memory().percent
    }

def export_health_report(filepath: str, report_content: str, metrics: Dict[str, Any]) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    md_text = f"""# KrokBot Workstation Health Report

**Generated**: {now}  
**OS Info**: {metrics.get('os_info', 'Unknown OS')}  

---

## System Metrics Baseline
* **CPU Usage**: {metrics.get('cpu_percent', 'N/A')}%
* **Memory Usage**: {metrics.get('memory_percent', 'N/A')}%

---

## Agent Diagnostic Summary

{report_content}

---
*Report generated by KrokBot Autonomous Diagnostic Agent.*
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_text)
